stages:
  prepare_30music:
    cmd: python src/dataprep/30music.py data/bronze/30music/sessions_sample_10.parquet.snappy
    deps:
    - data/bronze/30music/sessions_sample_10.parquet.snappy
    - src/dataprep/30music.py
    params:
    - prepare_30music.filter_last_months
    - prepare_30music.filter_topk
    outs:
    - data/silver/30music
